# Generated by Django 3.2.4 on 2022-04-04 17:56

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='photos/device')),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Running', 'Running')], max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('current_release', models.CharField(max_length=30)),
                ('target_release', models.CharField(max_length=30)),
                ('release_police', models.CharField(blank=True, choices=[('defult', 'defult'), ('recommand', 'recommand')], max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=200)),
                ('host_version', models.CharField(blank=True, max_length=200)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('all_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.all_type')),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('device_image', models.ImageField(blank=True, upload_to='photos/device_type')),
            ],
            options={
                'verbose_name': 'device_type',
                'verbose_name_plural': 'device_types',
            },
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Running', 'Running')], default='Online', max_length=50, null=True)),
                ('release', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.device')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service_type')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device_type'),
        ),
    ]
